version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: EmployeeDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: custom_password

  web:
    build: .
    command:       
      - sh
      - -c
      - |
        python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
